
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:14 (project)"
    message: |
      The system is: Darwin - 22.5.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:14 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/homebrew/Cellar/emscripten/3.1.44/libexec/emcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.wasm"
      
      The C compiler identification could not be found in:
        /Users/wjk/Code/previous-code/CMakeFiles/3.27.2/CompilerIdC/a.out
      
      The C compiler identification is Clang, found in:
        /Users/wjk/Code/previous-code/CMakeFiles/3.27.2/CompilerIdC/a.wasm
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:14 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /opt/homebrew/Cellar/emscripten/3.1.44/libexec/em++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.wasm"
      
      The CXX compiler identification could not be found in:
        /Users/wjk/Code/previous-code/CMakeFiles/3.27.2/CompilerIdCXX/a.out
      
      The CXX compiler identification is Clang, found in:
        /Users/wjk/Code/previous-code/CMakeFiles/3.27.2/CompilerIdCXX/a.wasm
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:14 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/wjk/Code/previous-code/CMakeFiles/CMakeScratch/TryCompile-aW8ZGV"
      binary: "/Users/wjk/Code/previous-code/CMakeFiles/CMakeScratch/TryCompile-aW8ZGV"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_ARCHITECTURES: "x86_64;arm64"
      CMAKE_OSX_DEPLOYMENT_TARGET: "10.13"
      CMAKE_OSX_SYSROOT: "/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/wjk/Code/previous-code/CMakeFiles/CMakeScratch/TryCompile-aW8ZGV'
        
        Run Build Command(s): /opt/homebrew/Cellar/cmake/3.27.2/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_aadce/fast
        /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_aadce.dir/build.make CMakeFiles/cmTC_aadce.dir/build
        Building C object CMakeFiles/cmTC_aadce.dir/CMakeCCompilerABI.c.o
        /opt/homebrew/Cellar/emscripten/3.1.44/libexec/emcc   -arch x86_64 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=10.13   -v -Wl,-v -MD -MT CMakeFiles/cmTC_aadce.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_aadce.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_aadce.dir/CMakeCCompilerABI.c.o -c /opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeCCompilerABI.c
         "/opt/homebrew/Cellar/emscripten/3.1.44/libexec/llvm/bin/clang" --version
        emcc: error: x86_64: No such file or directory ("x86_64" was expected to be an input file, based on the commandline arguments provided)
        make[1]: *** [CMakeFiles/cmTC_aadce.dir/CMakeCCompilerABI.c.o] Error 1
        make: *** [cmTC_aadce/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.27.2/share/cmake/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:14 (project)"
    checks:
      - "Check for working C compiler: /opt/homebrew/Cellar/emscripten/3.1.44/libexec/emcc"
    directories:
      source: "/Users/wjk/Code/previous-code/CMakeFiles/CMakeScratch/TryCompile-n2Lxso"
      binary: "/Users/wjk/Code/previous-code/CMakeFiles/CMakeScratch/TryCompile-n2Lxso"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_ARCHITECTURES: "x86_64;arm64"
      CMAKE_OSX_DEPLOYMENT_TARGET: "10.13"
      CMAKE_OSX_SYSROOT: "/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/Users/wjk/Code/previous-code/CMakeFiles/CMakeScratch/TryCompile-n2Lxso'
        
        Run Build Command(s): /opt/homebrew/Cellar/cmake/3.27.2/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_9dc33/fast
        /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_9dc33.dir/build.make CMakeFiles/cmTC_9dc33.dir/build
        Building C object CMakeFiles/cmTC_9dc33.dir/testCCompiler.c.o
        /opt/homebrew/Cellar/emscripten/3.1.44/libexec/emcc   -arch x86_64 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=10.13 -MD -MT CMakeFiles/cmTC_9dc33.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_9dc33.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_9dc33.dir/testCCompiler.c.o -c /Users/wjk/Code/previous-code/CMakeFiles/CMakeScratch/TryCompile-n2Lxso/testCCompiler.c
        emcc: error: x86_64: No such file or directory ("x86_64" was expected to be an input file, based on the commandline arguments provided)
        make[1]: *** [CMakeFiles/cmTC_9dc33.dir/testCCompiler.c.o] Error 1
        make: *** [cmTC_9dc33/fast] Error 2
        
      exitCode: 2
...
